[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m ensurepip", "python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.start]
cmd = "cd rag && uvicorn api:app --host 0.0.0.0 --port $PORT"

